### ISSUE TITLE
Calendar is broken

### ISSUE THREAD

**Issue by MartinX3** [dreamwhite/bugtracker#18]
The LineageOS-Calendar (Etar) won't sync (Account settings mention a sync problem).
The Google Calendar can't get installed.
`[INSTALL_FAILED_SHARED_USER_INCOMPATIBLE: Package com.google.android.calendar has a signing lineage that diverges from the lineage of the sharedUserId]`

**Comment by dreamwhite** [comment]
Ouch, nevermind. Closing this issue
