### ISSUE TITLE
can't see macos recovery

### ISSUE THREAD

**Issue by phankhanhpvk** [dreamwhite/bugtracker#24]
please help me, i create usb install macos monterey by opencore guide and EFI of [repo](https://github.com/dreamwhite/dell-inspiron-5370-hackintosh). i installed BIOS firmware but i cant see macos recovery in OCB for install
![image](https://user-images.githubusercontent.com/39584844/188468074-d1686579-2cd3-4ba7-8e74-124db203deba.png)

**Comment by dreamwhite** [comment]
Hi, thank you so much for opening an issue here.
First of all, please attach your hardware specs. You can use the following template:

- CPU
- GPU
- MOBO/Laptop model
- BIOS version

Also please make sure that you have `HfsPlus.efi` enabled in the drivers

**Comment by phankhanhpvk** [comment]
@dreamwhite Thanks for reply, sorry for missing information.

- CPU: I5 - 8250U
- GPU: Radeon 530 ( im added boot-arg -wegnoegpu)
- Model: Dell Inspirion 5370
- BIOS version 1.22
`HideAuxiliary` is `true`
![image](https://user-images.githubusercontent.com/39584844/188478180-655753c0-46ef-4aa1-a26f-8720635d5cd4.png)

**Comment by dreamwhite** [comment]
No worries, it happens some times... Then if `HideAuxiliary` is enabled, press the spacebar and you'll see the hidden partitions. Let me know if it works :D

**Comment by phankhanhpvk** [comment]
@dreamwhite spacebar it really worked :D , but new problem. stuck in `IOG flags 0x3 (0x51)`

**Comment by dreamwhite** [comment]
> @dreamwhite spacebar it really worked :D , but new problem. stuck in `IOG flags 0x3 (0x51)`

Mmmmmh, it's most likely a graphics configuration issue. Have you edited your DVMT values?

**Comment by phankhanhpvk** [comment]
> > @dreamwhite spacebar it really worked :D , but new problem. stuck in `IOG flags 0x3 (0x51)`
> 
> Mmmmmh, it's most likely a graphics configuration issue. Have you edited your DVMT values?

I changed ig-platform-id to 0900A53E and im in macos installer

**Comment by dreamwhite** [comment]
> > > @dreamwhite spacebar it really worked :D , but new problem. stuck in `IOG flags 0x3 (0x51)`
> > 
> > 
> > Mmmmmh, it's most likely a graphics configuration issue. Have you edited your DVMT values?
> 
> I changed ig-platform-id to 0900A53E and im in macos installer

mmmh I don't think it's the right platform id to use. After all you have an i5-8250U

**Comment by phankhanhpvk** [comment]
@dreamwhite but if use `0000C087` OCB stuck :(

**Comment by phankhanhpvk** [comment]
oh im wrong, this true need is `00001659`
i see `device-id` is `16590000` in your config, why `ig-platform-id` u set to `0000C087`?

**Comment by dreamwhite** [comment]
> oh im wrong, this true need is `00001659` i see `device-id` is `16590000` in your config, why `ig-platform-id` u set to `0000C087`?

That's what Dortania suggested for UHD620 users :/ https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/kaby-lake.html#add-2

**Comment by phankhanhpvk** [comment]
@dreamwhite sorry for new comment, pls let me know [this](https://github.com/dreamwhite/dell-inspiron-5370-hackintosh/blob/master/Docs/BIOS/Inspiron5370_Vostro5370_5471_BIOS_v1_22_0_x64.exe) is BIOS custom or origin? if origin can you share me file customed

**Comment by dreamwhite** [comment]
No prob, that's the original one downloaded from Dell website. Never flashed custom BIOSes
