### ISSUE TITLE
F11 & F12 brightness keys not work

### ISSUE THREAD

**Issue by phankhanhpvk** [dreamwhite/bugtracker#27]
Hi, please help me, F11 & F12 brightness keys not work for me.
Let me know what you need for debug.
Thanks you so much

- CPU: I5 - 8250U
- GPU: Radeon 530 ( im added boot-arg -wegnoegpu)
- Model: Dell Inspirion 5370
- BIOS version 1.22

**Comment by dreamwhite** [comment]
Hi, as already stated in the repo, I decided to use `fn+F11` and `fn+F12` (fn lock mode is enabled via BIOS) as I wasn't satisfied with `BRT6` key map.
