### ISSUE TITLE
GoogleSyncAdapters stopped working

### ISSUE THREAD

**Issue by FoscoV** [dreamwhite/bugtracker#29]
Hi,
Gsync used to work on lineageos-microg-pioneer.
I found just now that it stopped a while ago (june '22) both for calendar and contacts.
It doesn't return any error.

After a while looking for the point I only found out that magisk version updated from v.22 to v.25 (as far as I remember I did it when LineageOS updated to 19.1).

May that be the point?

**Comment by dreamwhite** [comment]
Hi, thank you so much for opening an issue. As far as I know Magisk version shouldn't lead to any issue. May I ask you to check if the sync adapters are shown in the system apps?

**Comment by FoscoV** [comment]
Figured that mail answer would apper here. I got it wrong....
A week ago:
#####
Hi,

activity manager and app info list the adapters and mark them as "running", no error reported. Both have the required permissions.

excluded Magisk version, my best guess pointed to LineageOs19.1 (android 12).

I tried to edit the module zip installer updating the apks to the most recent version available the on apkmirror (target Android 12).

    uninstalled the module that worked till last june
    reboot
    installed the modified/updated module
    reboot

It doesn't work. I see the updated adapter running on the system while still no sync activity and no error.
My next try could be the ["raw" instal ](https://gist.github.com/dreamwhite/934e7d2bb9e1f2a89c5307485a5c3fb3).

**Comment by FoscoV** [comment]
I tried:
-contacts and calendar local backup
-remove the google account (Settings/password and account/)
-install magisk module GooglSyncAdapters
-add the GoogleAccount

Contacts Sync result as running AND declares a sync activity (SUCCESS)
Calendar Sync does not run. It doesn't figure within system apps (while the apk is in /system/app/GoogleCalendarSyncAdapter). I can find it but fairly smaller then expected (373k, the apk is 4.9M)

com.google.android.syncadapters.calendar result as a running process (ps -e | grep calendar in adb shell)

Tried the procedure with both the updated APK from apkmirror and the one released in the magisk module. I obtained the same result.

**Comment by FoscoV** [comment]
Just discovered that by default the sync app was limited in connection.
by setting/app/GoogleCalendarSyncAdapter/traffic i can enable the app networking.
That allowed the app to connect to the server, login the account, appear within the sync options and finally actually sync the calendars.

The issue was all on my system configuration side.

**Comment by dreamwhite** [comment]
Hi, sorry if I reply late, but after all the issue was enabling the network connectivity permission for the Sync Adapters right?

**Comment by FoscoV** [comment]
Yes,
enabled network allowed the magisk module to work.
I'm sorry: the issue raised is unrelated to the module.

Both the "manually updated" apks and the currently released ones suffered the same issue and worked after I fixed the system configuration.
It is VERY likely that renowal of the google account (deleting the account and logging in again) was completely useless.
Since the very beginning of this issue, the inconsistencies were likely due to sync apps unable to connect.

It took two weeks to find out that there was an app specific network cut off option enabled.

**Comment by dreamwhite** [comment]
Alright, thank you so much! I updated the installation notes for the module

Fixed in dreamwhite/gsync_adapters_for_magisk@6775314
