### ISSUE TITLE
Error Ventura

### ISSUE THREAD

**Issue by phankhanhpvk** [dreamwhite/bugtracker#33]
I have problem when install ventura.
brightness not work, i can't change brightness.
Sleep not work
what i need for report

I use repo EFI, no change 

CPU:  Intel Core i5-8250U @ 1.8 GHz
iGPU: Intel UHD Graphics 620
DGPU: AMD RADEON 520 2G
WiFi Card: BCM94360NG
OS: macOS Ventura 13 (22A380)
BIOS: v1.22

**Comment by dreamwhite** [comment]
Hi, since you have a dGPU, have you tried disabling it? You can achieve it with `-wegnoegpu` in `NVRAM/Add/7C436110-AB2A-4BBB-A880-FE41995C9F82/boot-args`

For the sleep instead, have you ran the commands that @dortania suggests?

```
sudo pmset autopoweroff 0
sudo pmset powernap 0
sudo pmset standby 0
sudo pmset proximitywake 0
sudo pmset tcpkeepalive 0
```

**Comment by phankhanhpvk** [comment]
i know my problem, i disable gpu and all work now, thanks you

**Comment by dreamwhite** [comment]
Wonderful! Hope you enjoyed my EFI 😄 Feel free to buy me a coffee in the sponsors page
