### ISSUE TITLE
Issue in stats readme: missing image with link to anuraghazra

### ISSUE THREAD

**Issue by perez987** [dreamwhite/bugtracker#34]
Good morning, not an issue of the bugtracker or any repo but the reader file of the GitHub Reader Stats: I don't see the image containing the link to anuraghazra. Don't know where to post this so I decided to do it here.
Have a good day!

![anuraghazra link](https://user-images.githubusercontent.com/50429399/200810982-7c67ea87-0f71-4de7-bb9c-1f815783426f.png)

**Comment by dreamwhite** [comment]
Hi, well on my side it gets loaded:

![image](https://user-images.githubusercontent.com/17933708/200811233-e0b09ea2-0d5f-4575-bff7-519e08dc384b.png)

**Comment by perez987** [comment]
Yes, I see it ok right now, I don't know why I didn't see it before. Thanks!
