### ISSUE TITLE
don't get .hdr files from Dell_PFS_Extract.py & Universal-IFR-Extractor archived repo

### ISSUE THREAD

**Issue by nononymousse** [dreamwhite/bugtracker#36]
Hi \^^

I wanted to remove CFG Lock from my BIOS [Latitude_E6420_E6420ATG_A25.exe.zip](https://github.com/dreamwhite/bugtracker/files/10637447/Latitude_E6420_E6420ATG_A25.exe.zip) but when i extract it, i don't get .hdr files like your guide say but a bunch of .bin files instead

![Capture d’écran 2023-02-06 à 04 14 16](https://user-images.githubusercontent.com/32956707/216875998-fb908128-83d3-4bf6-aa8c-d1475ecf220e.png)

I have tried continuning following you guide, you ask to open the payload in UEFITool which is supposed being the largest file. I did put "1 Latitude_E6420_E6420ATG_A25 -- 11 Intel Management Engine Update v7.1.91.3272.bin" but i got this 

![Capture d’écran 2023-02-06 à 04 16 52](https://user-images.githubusercontent.com/32956707/216876656-906f953c-52ee-4d4f-aeda-081b3c5618c6.png)

I have also tested with "1 Latitude_E6420_E6420ATG_A25 -- 1 System BIOS vA.25.bin" and got a lot of things but searching for "CFG Lock" result in nothing (same for the Intel Management Engine Update file), tho i have searched for CFG and got a lot of result but don't know where to look

-----

On another note, Universal-IFR-Extractor (IFRExctract) repo got archived and from the last post on the issue page, it will not be updated anymore and they won't answer any issues from this repo. They advice to go to 
FRExtractor-RS ([https://github.com/LongSoft/IFRExtractor-RS](url)) instead. I thought you could update that link

Thank you and have a good day

**Comment by dreamwhite** [comment]
Hi thank you so much for opening this issue. I tested your attached BIOS update file, but I cannot find the CFG Lock.
I don't know if it's probably an issue specific of your model or every pre-Skylake hardware.

I'm closing this issue since there's nothing I can do about this.


> I wanted to remove CFG Lock from my BIOS [Latitude_E6420_E6420ATG_A25.exe.zip](https://github.com/dreamwhite/bugtracker/files/10637447/Latitude_E6420_E6420ATG_A25.exe.zip) but when i extract it, i don't get .hdr files like your guide say but a bunch of .bin files instead

The Python3 script doesn't extract any `.hdr` file, but rather `.bin` files. Going to fix it.

> On another note, Universal-IFR-Extractor (IFRExctract) repo got archived and from the last post on the issue page, it will not be updated anymore and they won't answer any issues from this repo. They advice to go to
> FRExtractor-RS ([https://github.com/LongSoft/IFRExtractor-RS](url)) instead. I thought you could update that link

I gotta test it but I'm pretty sure it'll work. As with the previous note, I'll commit it once fixed.

Thanks
dreamwhite
