### ISSUE TITLE
Stucks at LOG:EXITBS:START

### ISSUE THREAD

**Issue by michuapps** [dreamwhite/bugtracker#37]
Hi, I've got almost same setup as yours except for the drive. I have vostro 5370
[opencore-2023-03-10-140153.txt](https://github.com/dreamwhite/bugtracker/files/10942358/opencore-2023-03-10-140153.txt)

**Comment by dreamwhite** [comment]
Hi, thank you so much for opening an issue. Actually your laptop has a different ACPI set as well as potentially different BIOS offsets. 

In any case, are you using my latest EFI right?

**Comment by michuapps** [comment]
Yep, I'm using your latest EFI, I tried different settings such as disabling DevirtualiseMmio and enabling other fields. Speaking of bios, I've installed .exe file you posted in this repo and tried to follow your guide, but I could not find those offsets in extracted BIOS.

I remember, that couple years ago I managed to hackintosh this laptop but I can't remember if I was using your EFI or if I was using clover

**Comment by michuapps** [comment]
Alright,

After uncounted hours of digging I finally managed to boot to macOS recovery and install it.
From what I remember, I had to disable CFG Lock using your guide, and ENABLE intel SGX in bios despite the fact that Dortania's guide says it should be disabled.
Now I'm using your EFI + AirportItlwm and everything works fine for now. I just don't know how to map brightness keys on my keyboard. I'm still learning how to use this OS and I'm very excited for now.

If you have any tips or advices on what should I test or do after installing macOS that would be cool :)

P.s.
While changing BIOS offsets I bricked my laptop for a while :D but I managed to recover BIOS by installing it directly to the chip on mobo, after that I was more carefull.

**Comment by dreamwhite** [comment]
I'm glad you succeeded installing macOS on this PC. Hope you enjoy my EFI.

> I just don't know how to map brightness keys on my keyboard. I'm still learning how to use this OS and I'm very excited for now.

To be fair I abandoned mapping brightness keys and I'm using F11 and F12 (with fn lock enabled if I remember correctly) and they work smooth. I know it's not the same of a native brightness key, but who cares, it works!

Anyway closing this issue until more problems appear
