### ISSUE TITLE
Vostro 5370 Bios Extraction

### ISSUE THREAD

**Issue by CobanRamo** [dreamwhite/bugtracker#38]
Hi Ivan,
I have a few questions, have the same laptop here and your repo is really good.

1. ~~ask how do i extract this stupid dell bios? The script you linked doesn't work for me, what am I doing wrong?~~
![extraction_fail](https://user-images.githubusercontent.com/68192365/233463775-e3c51e89-2cc1-425d-b6df-b4fe3ed933e3.png)
edit:
is done.  sudo python3 Dell_PFS_Extract.py <BIOS_UPGRADE.EXE> would be correct...

2. Do you have any idea how to wake up this laptop from sleep or standby with keyboard or touchpad?
It doesn't wake up with either, only with the power button.
I would be really interested in how to wake up these laptops from sleep via TouchPad.

3. The PowerButton; Is there any way to get it to show up in sleep or standby mode with an LED?

Do you have any tips?
Thank you for your effort.

**Comment by dreamwhite** [comment]
Good morning, and thank you so much for opening an issue.

Let's breakdown the problems:

1. Cannot extract the BIOS:

The correct syntax to use is `python3 Dell_PFS_Extract.py <BIOS_UPGRADE.EXE>`. In the screenshot you kindly attached, it reports a missing module so theoretically you should run `pip3 install common` and it should do the trick. Can you confirm me it works?

2. Waking laptop from sleep or standby with keyboard or touchpad

Personally I never deep dived onto this topic, but when I had sleep enabled on my laptop I had to press the power button and it woke up from the sleep state. Make sure that you run previously the following commands:

```bash
sudo pmset autopoweroff 0
sudo pmset powernap 0
sudo pmset standby 0
sudo pmset proximitywake 0
sudo pmset tcpkeepalive 0
```

3. Enable power button led report status when in sleep/standby mode

Personally never noticed it. I think it's something related to ACPI stuff, as I saw it in other laptop repos, but can't really guide you through it, sorry. 

Is there anything else I can help you with?
